# Generated by Django 4.1 on 2024-04-22 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Ownerapp', '0007_tbl_turftime'),
        ('Guestapp', '0002_tbl_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_booking',
            fields=[
                ('bookingid', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(null=True)),
                ('amount', models.BigIntegerField()),
                ('status', models.CharField(max_length=100)),
                ('customerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guestapp.tbl_customer')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ownerapp.tbl_turftime')),
                ('turfid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ownerapp.tbl_turf')),
            ],
        ),
    ]
