# Generated by Django 4.1 on 2024-04-22 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customerapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_payment',
            fields=[
                ('paymentid', models.AutoField(primary_key=True, serialize=False)),
                ('billno', models.BigIntegerField(null=True)),
                ('totalamount', models.BigIntegerField(null=True)),
                ('status', models.CharField(max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('bookingid', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Customerapp.tbl_booking')),
            ],
        ),
    ]
