# Generated by Django 4.1 on 2024-04-23 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0005_tbl_size'),
        ('Customerapp', '0002_tbl_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_booking',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminapp.tbl_time'),
        ),
    ]
