# Generated by Django 4.1 on 2024-04-02 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Adminapp', '0005_tbl_size'),
        ('Guestapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_Turf',
            fields=[
                ('TurfId', models.AutoField(primary_key=True, serialize=False)),
                ('TurfName', models.CharField(max_length=40)),
                ('RegDate', models.CharField(max_length=40)),
                ('Image', models.ImageField(upload_to='')),
                ('Description', models.CharField(max_length=40)),
                ('Amount', models.CharField(max_length=40)),
                ('CategoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminapp.tbl_category')),
                ('OwnerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guestapp.tbl_owner')),
                ('Size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminapp.tbl_size')),
            ],
        ),
    ]
