# Generated by Django 4.1 on 2024-04-02 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ownerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_turf',
            name='Amount',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='tbl_turf',
            name='Description',
            field=models.CharField(max_length=2000),
        ),
    ]
