# Generated by Django 4.1 on 2024-04-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ownerapp', '0003_tbl_turf_locationid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_turf',
            name='RegDate',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
