# Generated by Django 4.1 on 2024-04-02 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ownerapp', '0004_alter_tbl_turf_regdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_turf',
            name='RegDate',
        ),
    ]
