# Generated by Django 4.1 on 2024-04-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ownerapp', '0005_remove_tbl_turf_regdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_turf',
            name='RegDate',
            field=models.DateField(auto_now=True),
        ),
    ]
