# Generated by Django 4.1 on 2024-02-26 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_District',
            fields=[
                ('DistrictId', models.AutoField(primary_key=True, serialize=False)),
                ('DistrictName', models.CharField(max_length=50)),
            ],
        ),
    ]
