# Generated by Django 4.1 on 2024-03-05 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_Location',
            fields=[
                ('LocationId', models.AutoField(primary_key=True, serialize=False)),
                ('LocationName', models.CharField(max_length=50)),
                ('DistrictId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminapp.tbl_district')),
            ],
        ),
    ]
