# Generated by Django 4.1 on 2024-03-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0002_tbl_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_Category',
            fields=[
                ('CategoryId', models.AutoField(primary_key=True, serialize=False)),
                ('CategoryName', models.CharField(max_length=50)),
                ('CategoryImage', models.ImageField(upload_to='')),
            ],
        ),
    ]
