# Generated by Django 4.1 on 2024-03-12 06:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Adminapp', '0004_tbl_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_Login',
            fields=[
                ('LoginId', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('Role', models.CharField(max_length=50)),
                ('Status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tbl_Owner',
            fields=[
                ('OwnerId', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('ContactNo', models.BigIntegerField()),
                ('Address', models.CharField(max_length=50)),
                ('OwnerPhoto', models.ImageField(upload_to='')),
                ('Dob', models.DateField()),
                ('Gender', models.CharField(max_length=50)),
                ('RegDate', models.DateField(default=datetime.date.today)),
                ('LocationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminapp.tbl_location')),
                ('LoginId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guestapp.tbl_login')),
            ],
        ),
    ]
