# Generated by Django 4.1 on 2024-04-08 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0005_tbl_size'),
        ('Guestapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_Customer',
            fields=[
                ('CustomerId', models.AutoField(primary_key=True, serialize=False)),
                ('CustomerName', models.CharField(max_length=50)),
                ('Phone', models.BigIntegerField()),
                ('Email', models.CharField(max_length=50)),
                ('RegDate', models.DateField(auto_now=True)),
                ('LocationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminapp.tbl_location')),
                ('LoginId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guestapp.tbl_login')),
            ],
        ),
    ]
