# Generated by Django 4.1 on 2024-05-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guestapp', '0002_tbl_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_owner',
            name='status',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
