# Generated by Django 4.1 on 2024-05-03 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guestapp', '0003_tbl_owner_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_turfpayment',
            fields=[
                ('paymentid', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.BigIntegerField()),
                ('status', models.CharField(max_length=50)),
                ('ownerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guestapp.tbl_owner')),
            ],
        ),
    ]
